src/Croostille/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include, url

from django.contrib import admin
from django.urls import path

from django.urls import path, include

from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='homepage.html'), name='homepage'),
    path('admin/', admin.site.urls),
    path('challenges/',include('courses.urls',namespace='courses')),
    path('offres/',include('memberships.urls',namespace='memberships')),
    path('auth/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
       url(r'^__debug__/', include(debug_toolbar.urls)),
   ]
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/courses/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path

from .views import CourseListView,CourseDetailView,WeekDetailView

app_name='courses'

urlpatterns = [
    path('', CourseListView.as_view(),name='liste'),
    path('<slug>', CourseDetailView.as_view(),name='detail'),
    path('<challenge_slug>/<week_slug>', WeekDetailView.as_view(),name='week_detail'),
]

src/memberships/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path

from .views import MembershipSelectView,PaymentView,updateTransactions,profile_view,cancelSubscription,UserCreateProfile

app_name='memberships'

urlpatterns = [
    path('', MembershipSelectView.as_view(),name='offres'),
    path('paiement/', PaymentView,name='paiement'),
    path('update-transactions/<subscription_id>', updateTransactions,name='update-transactions'),
    path('profile/', profile_view,name='profil'),
    path('createProfile/', UserCreateProfile.as_view(),name='creer_profil'),
    path('cancel/', cancelSubscription,name='annuler'),
]

src/courses/models.py
from django.db import models

from django.urls import reverse

from memberships.models import Membership

# Create your models here.
class Challenge(models.Model):
    slug=models.SlugField()
    title=models.CharField(max_length=120)
    description=models.TextField()
    allowed_memberships=models.ManyToManyField(Membership)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("courses:detail", kwargs={"slug": self.slug})

    @property
    def weeks(self):
        return self.week_set.all().order_by('position')

class Week(models.Model):
    slug=models.SlugField()
    title=models.CharField(max_length=120)
    challenge=models.ForeignKey(Challenge, on_delete=models.SET_NULL, null=True)
    position=models.IntegerField()
    description=models.TextField()
    video_url=models.CharField(max_length=200)
    thumbnail=models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("courses:week_detail", kwargs={
            'challenge_slug': self.challenge.slug,
            'week_slug':self.slug
        })

class Module(models.Model):
    slug=models.SlugField()
    title=models.CharField(max_length=120)
    week=models.ForeignKey(Week, on_delete=models.SET_NULL, null=True)
    position=models.IntegerField()
    description=models.TextField()
    video_url=models.CharField(max_length=200)
    thumbnail=models.ImageField()

    def __str__(self):
        return self.title

src/memberships/models.py
from django.db import models
from django.conf import settings

from django.db.models.signals import post_save

import stripe

from datetime import datetime

stripe.api_key=settings.STRIPE_SECRET_KEY


MEMBERSHIP_CHOICES=(
    ('Reduit','reduit'),
    ('Normal','normal')
)

# Create your models here.
class Membership(models.Model):
    slug=models.SlugField()
    membership_type=models.CharField(choices=MEMBERSHIP_CHOICES,max_length=30,default='Normal')
    price=models.IntegerField(default=20)
    stripe_plan_id=models.CharField(max_length=40)

    def __str__(self):
        return self.membership_type

class UserMembership(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id=models.CharField(max_length=40)
    membership=models.ForeignKey(Membership, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.user.username

def post_save_usermembership_create(sender,instance,created,*args,**kwargs):
    if created:
        UserMembership.objects.get_or_create(user=instance)
    
    user_membership,created=UserMembership.objects.get_or_create(user=instance)

    if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id=='':
        new_customer_id=stripe.Customer.create(email=instance.email)
        user_membership.stripe_customer_id=new_customer_id['id']
        user_membership.save()

post_save.connect(post_save_usermembership_create,sender=settings.AUTH_USER_MODEL)

class Subscription(models.Model):
    user_membership=models.ForeignKey(UserMembership, on_delete=models.CASCADE)
    stripe_subscription_id=models.CharField(max_length=40)
    active=models.BooleanField(default=True)


    def __str__(self):
        return self.user_membership.user.username
    
    @property
    def get_created_date(self):
        subscription=stripe.Subscription.retrieve(self.stripe_subscription_id)
        return datetime.fromtimestamp(subscription.created)

    @property
    def get_next_billing_date(self):
        subscription=stripe.Subscription.retrieve(self.stripe_subscription_id)
        return datetime.fromtimestamp(subscription.current_period_end)

src/memberships/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm,CheckboxInput
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(label = "Email")
    fullname = forms.CharField(label = "First name")

    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'fullname','email')

src/memberships/views.py
from django.shortcuts import render,redirect

from django.contrib import messages

from django.views.generic import ListView
from django.views import generic
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm

from django.conf import settings

from .models import Membership, UserMembership, Subscription
from django.contrib.auth.models import AnonymousUser,User

from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django.urls import reverse
from django.urls import reverse_lazy

from django.http import HttpResponse, HttpResponseRedirect, request

import stripe



def userHomepage(request):
    return render(request,'memberships/homepage.html')

def userConnect(request):
    return render(request,'memberships/registration/login.html')

def userDisconnect(request):
    logout(request)
    return redirect('homepage')

def profile_view(request):
    user_membership=get_user_membership(request)
    user_subscription=get_user_subscription(request)
    context={
        'user_membership':user_membership,
        'user_subscription':user_subscription
    }
    return render(request,"memberships/profile.html", context)

def get_user_membership(request):
    if AnonymousUser.is_anonymous:
        return request.session.get('membership_type')
    else:
        user_membership_queryset=UserMembership.objects.filter(user=request.user)
        if user_membership_queryset.exists():
            print("user membership:"+user_membership_queryset.first())
            return user_membership_queryset.first()
    return None

def get_user_subscription(request):
    user_subscription_queryset=Subscription.objects.filter(
        user_membership=get_user_membership(request)
    )
    if user_subscription_queryset.exists():
        user_subscription=user_subscription_queryset.first()
        print("user subscription:"+user_subscription_queryset.first())
        return user_subscription
    return None

def get_selected_membership(request):
    membership_type=request.session['membership']
    selected_membership_queryset=Membership.objects.filter(
            membership_type=request.POST.get('membership_type')
        )
    if selected_membership_queryset.exists():
        return selected_membership_queryset.first()
    else:
        return request.session.get('membership')
    return None

def get_stripe_id(request,name):
    selected_membership_queryset=Membership.objects.filter(
            membership_type=name
        )
    return selected_membership_queryset.first()

class UserCreateProfile(generic.CreateView):
    def get_membership(request):
        membership = request.session.get('membership')
    
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('memberships:paiement')
    template_name = 'memberships/registration/userCreateProfile.html'

class MembershipSelectView(ListView):
    model = Membership

    def get_context_data(self, *args, **kwargs):
        if not AnonymousUser.is_anonymous:
            context=super().get_context_data(**kwargs)
            current_membership=get_user_membership(self.request)
            context['current_membership']=str(current_membership.membership)
            return context
        else:
            context=super().get_context_data(**kwargs)
            return context
    
    def post(self, request, **kwargs):
        if AnonymousUser.is_anonymous:
            membership_type=request.POST.get('membership_type')
            request.session['membership']=membership_type
            return HttpResponseRedirect('createProfile')
        else:
            selected_membership_type=request.POST.get('membership_type')

            user_membership=get_user_membership(request)
            user_subscription=get_user_subscription(request)

            selected_membership_queryset=Membership.objects.filter(
                membership_type=request.POST.get('membership_type')
            )
            if selected_membership_queryset.exists():
                selected_membership=selected_membership_queryset.first()

            if user_membership.membership==selected_membership:
                if user_subscription != None:
                    messages.info(request,"Vous êtes déjà abonné à cette formule")
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            
            request.session['selected_membership_type']=selected_membership.membership_type

            return HttpResponseRedirect(reverse('memberships:paiement'))

def PaymentView(request):
    user_membership_queryset=UserMembership.objects.filter(user=request.user)
    user_membership=user_membership_queryset.first()
    selected_membership=get_selected_membership(request)
    stripe_plan=get_stripe_id(request,selected_membership)

    publishKey=settings.STRIPE_PUBLISHABLE_KEY

    if request.method=="POST":
        try:
            token=request.POST['stripeToken']
            subscription= stripe.Subscription.create(
                customer=user_membership.stripe_customer_id,
                items=[
                    {
                        "plan": stripe_plan
                    },
                ],
                default_source=token,
            )

            return redirect(reverse('memberships:update-transactions',
                kwargs={
                    'subscription_id': subscription.id
                }
            ))

        except stripe.error.CardError as e:
            messages.info(request,"Votre carte a été rejetée.")


    context={
        'publishKey':publishKey,
        'selected_membership':selected_membership
    }

    return render(request, 'memberships/membership_payment.html',context)

def updateTransactions(request, subscription_id):
    user_membership=get_user_membership(request)
    selected_membership=get_selected_membership(request)

    user_membership.membership=selected_membership
    user.membership.save()

    sub, created=Subscription.objects.get_or_create(user_membership=user_membership)
    sub.stripe_subscription_id=subscription_id
    sub.active=True 
    sub.save()

    try:
        del request.session['selected_membership_type']
    except:
        pass

    messages.info(request,"L'abonnement {} a bien été crée.".format(selected_membership))
    return redirect('/courses')

def cancelSubscription(request):
    user_subscription=get_user_subscription(request)

    if user.active==False:
        messages.info(request,"Vous n'avez pas d'abonnement en cours.")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    sub=stripe.Subscription.retrieve(user_sub.stripe_subscription_id)
    sub.delete()

    user_subscription.active=False
    user_subscription.save()

    messages.info(request,"Votre abonnement a bien été annulé.")

    return HttpResponseRedirect('memberships/')

src/memberships/templates/memberships/homepage.html
{% extends "courses/base.html"%}

{% block title %}
    Croostille : accueil
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        Bonjour {{ user.username }}.
        <p><a href="{% url 'logout' %}">Se déconnecter</a></p>
        <p><a href="{% url 'password_reset' %}">Changer mon mot de passe</a></p>
    {% else %}
    <p>Vous n'êtes pas connecté(e)</p>
    <a href="{% url 'login' %}">Se connecter</a> |
    <a href='/offres'>S'inscrire</a>
    {% endif %}

{% endblock %}

src/memberships/templates/memberships/membership_list.html
{% extends 'courses/base.html' %}

{% block content %}

<div class="Container">
    <h1>Choisissez une offre</h1>
    <div class="row">
        {% for object in object_list%}

            <div class="col-sm-4 col-md-4">
                {{ object.membership_type }}
                <br/>Prix: {{ object.price }}<small> par mois</small>
                <h4>Inclus dans le prix:</h4>
                <ul>
                    {% for challenge in object.challenge_set.all %}
                        <li>{{ challenge.title }}</li>
                    {% endfor %}
                </ul>
                    
                        <form method="POST" action="{% url 'memberships:offres' %}">

                        {% csrf_token %}
                        {% if request.user.is_authenticated %}
                            {% if object.membership_type != current_membership %}
                                <button class="btn btn-warning">Je m'inscris</button>
                                <input type="hidden" name="membership_type" value="{{ object.membership_type }}">
                            {% else %}
                                <small>Il s'agit de votre abbonnement actuel</small>
                            {% endif %}
                            <input type="hidden" name="membership_type" value="{{ object.membership_type }}">
                        {% else %}
                            <button class="btn btn-warning">Je m'inscris</button>
                            <input type="hidden" name="membership_type" value="{{ object.membership_type }}">
                        {% endif %}
                        </form>
                    
                        
                    
            </div>

        {% endfor %}
    </div>

</div>

{% endblock content %}

src/memberships/templates/memberships/membership_payment.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/checkout.css' %}">

<div class="container">
    <div class="row">
        <h1>Paiement</h1>
            <p>Abonnement choisi: {{ selected_membership }}</p>
            <p>Prix: {{ selected_membership.price }} euros/mois</p>


            <button onclick="toggleDisplay();" class="btn btn-warning" style="width: 100%;">Checkout with a credit card</button>

            <div id="collapseStripe" class="wrapper">
                <script src="https://js.stripe.com/v3/"></script>

                <!-- can't do this -->
                <!-- <script src="{% static 'js/stripeV3.js' %}"></script> -->

                <form action="." method="post" id="payment-form">
                    {% csrf_token %}
                    <div id="checkoutMethods">
                    <div style="margin: 10px;">
                        <h2>Checkout with Stripe</h2>
                        <div class="form-row">
                        <label for="card-element">
                            Credit or debit card
                        </label>
                        <div id="card-element" class="w-100 StripeElement StripeElement--empty"><div class="__PrivateStripeElement" style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;"><iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame3" allowpaymentrequest="true" src="https://js.stripe.com/v3/elements-inner-card-8a434729e4eb82355db4882974049278.html#style[base][color]=%2332325d&amp;style[base][lineHeight]=18px&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;features[noop]=false&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js%2Felements%2Fquickstart&amp;controllerId=__privateStripeController0" title="Secure payment input frame" style=""></iframe><input class="__PrivateStripeElement-input" aria-hidden="true" style=""><input class="__PrivateStripeElement-safariInput" aria-hidden="true" tabindex="-1" style=""></div></div>
                    
                        <!-- Used to display form errors. -->
                        <div id="card-errors" role="alert"></div>
                        </div>
                        <input type="hidden" id="nonce" name="payment_method_nonce" />
                    </div>
                    </div>
                    <button>Submit Payment</button>
                </form>
                
                </div>

                <div id="stripe-token-handler" class="is-hidden">Success! Got token: <span class="token"></span></div>

                </div>

                <!-- script for the stripe form -->
                <script src="{% static 'js/checkout.js' %}"></script>

                <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

                <script src="https://js.braintreegateway.com/web/dropin/1.13.0/js/dropin.min.js"></script>
                <script>
                var form = document.querySelector('#payment-form');
                var client_token = '{{ client_token }}';
                braintree.dropin.create({
                    authorization: client_token,
                    container: '#bt-dropin',
                    paypal: {
                    flow: 'vault'
                    }
                }, function (createErr, instance) {
                    form.addEventListener('submit', function (event) {
                    event.preventDefault();
                    instance.requestPaymentMethod(function (err, payload) {
                        if (err) {
                        console.log('Error', err);
                        return;
                        }
                        // Add the nonce to the form and submit
                        document.querySelector('#nonce').value = payload.nonce;
                        form.submit();
                    });
                    });
                });
                </script>

                <!-- script for toggling display of the form -->
                <script type="text/javascript">
                    function toggleDisplay() {
                    var x = document.getElementById("collapseStripe");
                    if (x.style.display === "none") {
                        x.style.display = "block";
                    } else {
                        x.style.display = "none";
                    }
                    };
                </script>



    </div>
</div>

{% endblock content %}

src/memberships/templates/memberships/profile.html
{% extends 'courses/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <h1>Mon profil</h1>
        <div>
            {% if user_subscription != None %}
                <h4>Abonnement: {{ user_membership.membership.membership_type}}</h4>
                <h4>Membre depuis: {{ user_subscription.get_created_date }}</h4>

                {% if user.subscription.active != False%}
                    <p>Votre prochain paiement est du le : {{ user_subscription.get_next_billing_date }}</p>
                    <p><a href="% url 'memberships:annuler' %">Annuler mon abonnement</a></p>

                {% else %}
                    <p>Vous n'êtes pas abonné(e)</p>
                    <p><a href="{% url 'memberships:offres' %}">Découvrir les offres</a></p>
                {% endif %}

            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}